<!doctype html>
<head>
<meta http-equiv="content-type" content="text/html;charset=utf-8" />
<link href="<?php echo ADMIN_STATIC_PATH; ?>css/global.css" type="text/css" rel="stylesheet" />
<script src="<?php echo ADMIN_STATIC_PATH; ?>js/jquery.js" type="text/javascript"></script>
<script src="<?php echo ADMIN_STATIC_PATH; ?>admin/js/global.js" type="text/javascript"></script>
<script type="text/javascript">
	var pKey = "{$_pkey}", urlKey = "{$_ukey}", place = "{$_place}";
</script>
<title>Yafcms后台</title>
</head>
<body>

<body>

<div class="m">
	<div class="p">
		<div class="cc">
			<div class="sky warning bnote"><i></i><b>好用告诉别人，不好用告诉<a href="http://www.twcms.com" target="_blank">我们</a>~</b></div>	
		</div>
	</div>
</div>

</body>
</html>