<!doctype html>
<head>
<meta http-equiv="content-type" content="text/html;charset=utf-8" />
<link href="<?php echo ADMIN_STATIC_PATH; ?>css/global.css" type="text/css" rel="stylesheet" />
<script src="<?php echo ADMIN_STATIC_PATH; ?>js/jquery.js" type="text/javascript"></script>
<script src="<?php echo ADMIN_STATIC_PATH; ?>admin/js/global.js" type="text/javascript"></script>
<script type="text/javascript">
	var pKey = "{$_pkey}", urlKey = "{$_ukey}", place = "{$_place}";
</script>
<title>Yafcms后台</title>
</head>
<body>

<div class="m">
	<div class="p">
		<div class="cc">
			<form action="index.php?u=my-password-ajax-1" method="post">
				<div class="tb_t">修改密码</div>
				<table class="tb">
					<tr>
						<th class="th">原密码</th>
						<td class="col"><input name="oldpw" type="password" class="inp w1" /></td>
					</tr>
					<tr>
						<th class="th">新密码</th>
						<td class="col"><input name="newpw" type="password" class="inp w1" /></td>
					</tr>
					<tr>
						<th class="th">确认密码</th>
						<td class="col"><input name="confirm_newpw" type="password" class="inp w1" /></td>
					</tr>
				</table>
				<div class="tb_b"><input type="submit" value="&#20445;&#23384;" class="but1" /></div>
			</form>
		</div>
	</div>
</div>

<script type="text/javascript">
twAjax.submit("form:first", function(data){
	twAjax.alert(data);
	if(window.twData.err==0) setTimeout("window.location.reload()",1000);
});
</script>
</body>
</html>
