<!doctype html>
<head>
<title>YafCms后台管理</title>
<meta http-equiv="content-type" content="text/html;charset=utf-8" />
<link href="{$smarty.const.resource_admin}/css/admin.css" type="text/css" rel="stylesheet" />
</head>

<body scroll="no">
<div class="acp">
	<div id="box_opt"><a id="ifr_refresh" title="刷新" href="">刷新</a> <a id="full_screen" title="全屏" href="">全屏</a></div>
	<div class="top">
		<div class="logo"><a href="./"><img src="{$smarty.const.resource_admin}/img/logo.jpg" /></a></div>
		<div class="nav">
			<ul>
				{loop:$_navs[0] $name $pKey}<li pKey="{$pKey}" tabindex="0" role="link">
					<b>{$name}</b>
					<dl>
						{loop:$_navs[2][$pKey] $arr $url}<dd urlKey="{$url}" tabindex="0" role="link">{$arr[name]}</dd>
						{/loop}<dt></dt>
					</dl>
				</li>
				{/loop}
			</ul>
		</div>
		<div class="uinfo">
			<p>您好, {$_user[username]}（{$_group[groupname]}）[<a href="index.php?u=index-logout">退出</a>]</p>
			<p class="ilk"><a href="../index.php" target="_blank" title="网站首页">网站首页</a></p>
		</div>
	</div>
	<div class="unber">
		<div class="left">
			<h1 id="menutit"></h1>
			<dl id="menu"></dl>
			<div class="copyright">Powered by Yafcms </div>
		</div>
		<div class="right">
			<div id="closeer" title="关闭其它标签页"></div>
			<div id="leftbtn" title="向上"></div>
			<div id="rightbtn" title="向下"></div>
			<div id="adder" title="新标签页"></div>
			<div id="box_tab"><ul></ul></div>
			<div id="box_place"></div>
			<div id="box_frame"></div>
		</div>
	</div>
</div>
<script src="<?php echo ADMIN_STATIC_PATH; ?>js/jquery.js" type="text/javascript"></script>
<script src="<?php echo ADMIN_STATIC_PATH; ?>js/admin.js" type="text/javascript"></script>
</body>
</html>
