<!doctype html>
<head>
<meta http-equiv="content-type" content="text/html;charset=utf-8" />
<link href="<?php echo ADMIN_STATIC_PATH; ?>css/global.css" type="text/css" rel="stylesheet" />
<script src="<?php echo ADMIN_STATIC_PATH; ?>js/jquery.js" type="text/javascript"></script>
<script src="<?php echo ADMIN_STATIC_PATH; ?>admin/js/global.js" type="text/javascript"></script>
<script type="text/javascript">
	var pKey = "{$_pkey}", urlKey = "{$_ukey}", place = "{$_place}";
</script>
<title>Yafcms后台</title>
</head>
<body>
<div class="m">
	<div class="p">
		<div class="cc">
			<form action="index.php?u=setting-attach-ajax-1" method="post">
				<div class="tb_t">上传设置</div>
				<table class="tb">
					<tr>
						<th class="th">上传图片</th>
						<td class="col">允许类型{$input[up_img_ext]} 最大限制{$input[up_img_max_size]}KB</td>
					</tr>
					<tr>
						<th class="th">上传附件</th>
						<td class="col">允许类型{$input[up_file_ext]} 最大限制{$input[up_file_max_size]}KB</td>
					</tr>

					{hook:admin_setting_attach_after.htm}

				</table>
				<div class="tb_b"><input type="submit" value="&#20445;&#23384;" class="but1" /></div>
			</form>
		</div>
	</div>
</div>

<script type="text/javascript">
twAjax.submit("form:first");
</script>
</body>
</html>
