<!doctype html>
<head>
<meta http-equiv="content-type" content="text/html;charset=utf-8" />
<link href="{$smarty.const.resource_admin}css/global.css" type="text/css" rel="stylesheet" />
<script src="<?php echo ADMIN_STATIC_PATH; ?>js/jquery.js" type="text/javascript"></script>
<script src="<?php echo ADMIN_STATIC_PATH; ?>admin/js/global.js" type="text/javascript"></script>
<script type="text/javascript">
	var pKey = "{$_pkey}", urlKey = "{$_ukey}", place = "{$_place}";
</script>
<title>Yafcms后台</title>
</head>
<body>